### ISSUE TITLE
HBase version requirement

### ISSUE THREAD

**Issue by AbhiMadav** [hortonworks/shc#16]
I was trying out the connector to work with HBase 1.0.0 and it fails with 

ERROR yarn.ApplicationMaster: User class threw exception: java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/util/DataTypeParser$
java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/util/DataTypeParser$

Could you please specify the minimum HBase requirement for the project?

**Comment by zhzhan** [comment]
Currently in the pom file, we use <hbase.version>1.1.1</hbase.version>. But it looks that the exception is caused by spark version mismatch, instead of hbase. The spark version currently supported is spark.version>1.6.0</spark.version>
